### ISSUE TITLE
examples/standalone repl prompt somehow broken

### ISSUE THREAD

**Issue by karme** [shirok/Gauche#1084] opened 2024-11-29 14:12 UTC
i can compile the sample-repl as standalone executable successfully but when I run it the prompt is broken:

```
$ ./sample-repl 
(+ Welcome to my standalone REPL application!
gosh$              (+ 1 2)
3
gosh$              (+ 1 2)
3
sample-repl> gosh$ 
```

note: somehow 2 prompts are displayed "sample-repl>" and "gosh$"

**Comment by shirok** [comment] 2024-11-30 05:50
Ah, `gauche.interactive` tries to start line-edit mode.

**Comment by shirok** [comment] 2024-11-30 22:50
A quick fix is either to remove `(use gauche.interactive)`, or just call `read-eval-print-loop` without argumetns.

We have two `read-eval-print-loop`, one in `gauche` and another in `gauche.interactive`.   The former is a plain-old repl, while the latter supports line-editing when the terminal is capable.  The root cause is that they have diferent ways to treat prompting.  I'll mull over if I can address that.

**Comment by shirok** [comment] 2024-12-03 10:33
It should have been fixed now.

**Closed by shirok** 2024-12-03 10:33 UTC

**Comment by karme** [comment] 2024-12-04 16:55
works for me - thanks!
