### ISSUE TITLE
rfc.tls test fails on Ubuntu 22.04

### ISSUE THREAD

**Issue by nkoguro** [shirok/Gauche#824] opened 2022-05-13 10:32 UTC
rfc.tls test fails on Ubuntu 22.04. ([test.log](https://gist.github.com/nkoguro/e509a50ea6162a545a71f2c9c561fd28))

kick_openssl.sh exits with this error.
```
% /home/naoki/work/Gauche/ext/tls/kick_openssl.sh s_server -cipher DEFAULT@SECLEVEL=1 -accept 19002 -quiet -cert /home/naoki/work/Gauche/ext/tls/axTLS/ssl/test/axTLS.x509_1024.pem -key /home/naoki/work/Gauche/ext/tls/axTLS/ssl/test/axTLS.key_1024.pem
Starting openssl in /home/naoki/work/Gauche/ext/tls
error setting certificate
40479BFF1B7F0000:error:0A00018E:SSL routines:SSL_CTX_use_certificate:ca md too weak:../ssl/ssl_rsa.c:221:
```

Linux and openssl versions are:
```
% uname -a
Linux ubuntu 5.15.0-30-generic #31-Ubuntu SMP Thu May 5 10:00:34 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
% openssl version
OpenSSL 3.0.2 15 Mar 2022 (Library: OpenSSL 3.0.2 15 Mar 2022)
```

**Comment by shirok** [comment] 2022-05-14 18:58
Confirmed.

**Comment by shirok** [comment] 2022-05-14 22:15
Looks like a bunch of old hash algorithms are obsoleted and rejected by newer openssl.

**Comment by shirok** [comment] 2022-05-15 09:07
Since axTLS hasn't been updated for a while, I'm thinking to drop it rather than patching it.  Few users care to choose TLS implementation, if any; most users would expect it "just work".

The reason I kept axTLS was that ti allows Gauche binary run without depending on external tls libary at runtime.  However, you can configure `--with-tls=mbedtls-internal` if you don't like that dependency.

**Comment by shirok** [comment] 2022-06-08 20:06
Closing.

**Closed by shirok** 2022-06-08 20:06 UTC
