### ISSUE TITLE
[SRFI 128] Gauche's default-hash does not except user-defined types

### ISSUE THREAD

**Issue by mnieper** [shirok/Gauche#708] opened 2020-08-03 15:57 UTC
The SRFI 128 `default-hash` procedure is supposed to accept any Scheme value but Gauche's implementation gives an error when applied to a user-defined record.

This also limits the usability of `eq?`-based SRFI 125 hash tables. SRFI 69 `eq?`-based hash-tables work fine.

**Comment by shirok** [comment] 2020-08-03 18:29
I see.  Gauche native eq?-based and eqv?-based tables uses specialized hash functions, but rereading relevant srfis, I reckon default-hash should fall back to eqv-based hash if specialized hash method isn't defined for the user defined type.

**Comment by mnieper** [comment] 2020-08-03 18:46
When the comparator equality relation is `eq?` or `eqv?` or generally a refinement of `equal?`, SRFI 125 hash-tables are allowed to ignore the hash function packaged in the comparator and use an implementation-defined hash function.

So for the `eq?`- and `eqv?`-based SRFI 125 hash tables Gauche can (and should probably) use the same implementation it does for the respective SRFI 69 hash tables.

**Comment by shirok** [comment] 2020-08-03 19:19
Ah, right.  I overlooked that part of the specification.

**Comment by shirok** [comment] 2020-08-05 04:07
The change 4392ec9 allows user-defined objects to be used in srfi-125 hash tables with eq? and eqv? equality predicate.

Handling arbitrary object in `default-hash` seems more tricky.  A user-defined object can have its own equality method `object-equal?`.    If we fall back to `eqv-hash` in `default-hash` could yield an incorrect result, when two user-defined object are equal in its own method yet their hash value differ.   The user code must define `object-hash` method if it has `object-equal?`, but we can't force it.

My intention was that letting `default-hash` fail would be a reminder for the user to define proper `object-hash`, but srfi-128 doesn't allow `default-hash` to fail.  I think the only choice is that, if a user-defined type defines `object-equal?` but not `object-hash`, `default-hash` returns a constant value.

**Comment by shirok** [comment] 2020-08-14 00:09
The issue is addressed as follows

- `default-hash` returns a constant value (depends on per-process salt value) for objects with unknown hash function.
- SRFI-125 hash tables that gets `eq?` or `eqv?` equality predicate uses built-in `eq-hash` or `eqv-hash`, regardless of the hash functions in the given comparator.

Closing.

**Closed by shirok** 2020-08-14 00:09 UTC
