### ISSUE TITLE
Can't install due to regexp-replace-all error in slib

### ISSUE THREAD

**Issue by nkoguro** [shirok/Gauche#506] opened 2019-08-09 09:13 UTC
When I try to install, regexp-replace-all fails in slib.

```
if test -f /usr/share/slib/require.scm && test x86_64-pc-linux-gnu = x86_64-pc-linux-gnu ; then \
  /home/naoki/.local/bin/gosh -ftest -uslib -E"require 'new-catalog" -Eexit;\
fi
gosh: "ERROR": regexp-replace-all: matching zero-length string causes infinite loop: "(/?)$"
Makefile:163: recipe for target 'slibcat' failed
make[1]: *** [slibcat] Error 1
```

**Comment by shirok** [comment] 2019-08-09 10:29
Indeed.

0.9.8:
gosh> (regexp-replace-all #/(\/?)$/ "/abc/def" "")
"/abc/def"
gosh> (regexp-replace-all #/(\/?)/ "/abc/def" "")
*** ERROR: regexp-replace-all: matching zero-length string causes infinite
loop: #/(\/?)/

HEAD:
gosh> (regexp-replace-all #/(\/?)$/ "/abc/def" "")
*** ERROR: regexp-replace-all: matching zero-length string causes infinite
loop: #/(\/?)$/
gosh> (regexp-replace-all #/(\/?)/ "/abc/def" "")
*** ERROR: regexp-replace-all: matching zero-length string causes infinite
loop: #/(\/?)/

We did change regexp-replace internals but this 'zero-length match'
condition is the same.   Hmm...

**Comment by pclouds** [comment] 2019-08-09 10:45
The old version does not check infinite on the first match (and returns the string as-is). The new version (sorry, my bad!) I think always checks inifinite. Perhaps that's the problem?

**Comment by shirok** [comment] 2019-08-09 10:55
Yes that's the difference, but it's debatable which one is the right
thing.  I think I'll change the offending pattern in lib/slib.scm to avoid
zero-length match.  However, this change can cause surprises for existing
code, so I'd like to keep the old behavior.

**Comment by pclouds** [comment] 2019-08-09 11:02
Agreed. I wonder if we should just always abort regexp-all and return instead of error out in the infinite case. There's some value in catching "bad" patterns, but I think the "inifite" condition may depend on the actual string as well, which could cause surprise errors.

**Comment by shirok** [comment] 2019-08-09 11:27
@nkoguro , could you try the above commit?

For the ultimate fix of regexp-replace(-all), we may want to check what other languages/implementations are doing.

**Comment by nkoguro** [comment] 2019-08-09 12:50
The commit 8fd786e5b worked.
Thanks!

**Comment by pclouds** [comment] 2019-08-09 13:34
On a related note. `regexp-fold` also has to deal with empty matches and I opted for moving forward by one char and trying again (*). It will terminate, but it may be a waste of CPU cycles. Whatever we will do with `regexp-replace-all`, we should probably do the same for `regexp-fold`

(*) I'm pretty sure it was because of some tests from chibi. But chibi's regexp-fold is a bit harder to crack to confirm the expected behavior here.

**Comment by pclouds** [comment] 2019-08-10 10:51
> For the ultimate fix of regexp-replace(-all), we may want to check what other languages/implementations are doing.

Links to [Various implementations](https://www.regular-expressions.info/zerolength.html) and [Javascript](http://www.regexguru.com/2008/04/watch-out-for-zero-length-matches/). Still not sure about Java.

The short summary is most implementations just advance by one past zero-length matches. Chibi regex I'm pretty sure is in this camp. IrRegex (used by Chicken) definitely does.

Perl/PCRE is more clever and can instruct the next match to exclude zero-length matches to avoid infinite loop, either you match something else, or you match nothing.

Scsh regex behaves like Gauche and will throw an error "An empty-string regexp match has put regexp-fold into an infinite loop."

**Comment by shirok** [comment] 2019-08-18 01:12
I adopted the way to increment one character before iteration, for it seems commonly accepted.
Closing.  Feel free to reopen if you find an issue with the solution.

**Closed by shirok** 2019-08-18 01:12 UTC
